#spring.datasource.url=jdbc:h2:file:./data/desafio
#spring.datasource.url=${DATABASE_URL}
#spring.datasource.url=${JDBC_DATABASE_URL}
#spring.datasource.url=jdbc:postgresql://dpg-d7leej1f9bms738igp4g-a/desafio_db_hax5?user=desafio_db_hax5_user&password=SKqOFnQrUVK2bevA8T4lk2fSxrpQud6E
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.url=${DB_URL}
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:postgresql://dpg-d7leej1f9bms738igp4g-a:5432/desafio_db_hax5?user=desafio_db_hax5_user&password=SKqOFnQrUVK2bevA8T4lk2fSxrpQud6E}
spring.datasource.driverClassName=org.postgresql.Driver


# H2 Console
spring.h2.console.enabled=false
spring.h2.console.path=/h2-console

# JPA
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#admin.email=milliance23@gmail.com
admin.email=${ADMIN_EMAIL:milliance23@gmail.com}

# Google OAuth2 JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://accounts.google.com
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://www.googleapis.com/oauth2/v3/certs

spring.mail.host=smtp.gmail.com
spring.mail.port=587
#spring.mail.username=connaissanceaction@gmail.com
#spring.mail.password=pipcyfcvywiffhox
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

#server.port = 8090
server.port=${PORT:8090}

#SSL, post 465
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory

spring.mail.protocol=smtp
spring.mail.defaultEncoding=UTF-8

spring.mail.properties.mail.smtp.socketFactory.fallback = false
spring.mail.properties.mail.smtp.ssl.enable=false

support.mail.address=connaissanceaction@gmail.com
#cors.allowed-origins=http://localhost:4200,http://localhost,https://gerenciamento-tarefas-angular-epvn2e7sf-han19githtbrs-projects.vercel.app
#CORS_ALLOWED_ORIGINS=https://gerenciamento-tarefas-angular.vercel.app,https://gerenciamento-tarefas-angular-hwlq2ta5x-han19githtbrs-projects.vercel.app
#cors.allowed-origins=http://localhost:4200,http://localhost,https://gerenciamento-tarefas-angular.vercel.app,https://gerenciamento-tarefas-angular-gde6vunv6-han19githtbrs-projects.vercel.app
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}
